spring:
  application:
         name: shop
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /luckyShop

mybatis:
  type-aliases-package: com.example.shop.bean
  mapper-locations: classpath:mappers/*.xml