package com.example.shop.service.vo;

public class FoodOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodorder.id
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodorder.title
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodorder.description
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodorder.price
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodorder.url
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodorder.id
     *
     * @return the value of foodorder.id
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodorder.id
     *
     * @param id the value for foodorder.id
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodorder.title
     *
     * @return the value of foodorder.title
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodorder.title
     *
     * @param title the value for foodorder.title
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodorder.description
     *
     * @return the value of foodorder.description
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodorder.description
     *
     * @param description the value for foodorder.description
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodorder.price
     *
     * @return the value of foodorder.price
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodorder.price
     *
     * @param price the value for foodorder.price
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodorder.url
     *
     * @return the value of foodorder.url
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodorder.url
     *
     * @param url the value for foodorder.url
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}