package com.example.shop.service.vo;

import java.math.BigDecimal;
import java.util.Date;

public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.id
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.name
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.stock
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.image_url
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.category
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.created_at
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.description
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.id
     *
     * @return the value of products.id
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.id
     *
     * @param id the value for products.id
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.name
     *
     * @return the value of products.name
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.name
     *
     * @param name the value for products.name
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.price
     *
     * @return the value of products.price
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.price
     *
     * @param price the value for products.price
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.stock
     *
     * @return the value of products.stock
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.stock
     *
     * @param stock the value for products.stock
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.image_url
     *
     * @return the value of products.image_url
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.image_url
     *
     * @param imageUrl the value for products.image_url
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.category
     *
     * @return the value of products.category
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.category
     *
     * @param category the value for products.category
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.created_at
     *
     * @return the value of products.created_at
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.created_at
     *
     * @param createdAt the value for products.created_at
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.description
     *
     * @return the value of products.description
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.description
     *
     * @param description the value for products.description
     *
     * @mbg.generated Fri May 23 12:39:59 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}