package com.example.shop.dao;

import com.example.shop.service.vo.FoodOrder;
import java.util.List;

public interface FoodOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodorder
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodorder
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    int insert(FoodOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodorder
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    FoodOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodorder
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    List<FoodOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodorder
     *
     * @mbg.generated Fri May 23 16:34:47 CST 2025
     */
    int updateByPrimaryKey(FoodOrder row);
}